#!/bin/bash

function atom-backup {
  # Back up files in atom config directory, ignoring subdirectories
  rsync -av -f"- */" -f"+ *" ~/.atom/ $DEV_TOOLS/settings/atom

  # Save list of currently installed atom packages
  apm list --installed --bare > $DEV_TOOLS/settings/atom/package-list.txt
}

function atom-restore {
  # Write atom directory contents to config directory
  rsync -av $DEV_TOOLS/settings/atom/ ~/.atom

  # Install atom packages
  apm install --packages-file ~/.atom/package-list.txt
}
